app = "facturacion-universal"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[processes]
  app = "dotnet Facturacion.Api.dll"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = ""

[kill_signal]
  signal = "SIGTERM"

[kill_timeout]
  timeout = 30
