// <auto-generated />
using System;
using Facturacion.Infraestructura.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Facturacion.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605213654_AddIdempotencyKeys")]
    partial class AddIdempotencyKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facturacion")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Facturacion.Core.Entidades.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FechaExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expira");

                    b.Property<int>("MaxEmpresas")
                        .HasColumnType("integer")
                        .HasColumnName("max_empresas");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("integer")
                        .HasColumnName("max_usuarios");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("cuentas", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Empresa", b =>
                {
                    b.Property<string>("Ruc")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ruc");

                    b.Property<string>("CertPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cert_password");

                    b.Property<string>("CertificadoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificado_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("DirMatriz")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dir_matriz");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logo_content_type");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Ruc");

                    b.HasIndex("CuentaId");

                    b.ToTable("empresas", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ambiente");

                    b.Property<decimal?>("BaseImponibleIce")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_imponible_ice");

                    b.Property<decimal>("BaseImponibleIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_imponible_iva");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("clave_acceso");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirEstablecimiento")
                        .HasColumnType("text")
                        .HasColumnName("dir_establecimiento");

                    b.Property<string>("DireccionComprador")
                        .HasColumnType("text")
                        .HasColumnName("direccion_comprador");

                    b.Property<string>("EmpresaRuc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("empresa_ruc");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estab");

                    b.Property<string>("EstadoCorreo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_correo");

                    b.Property<string>("EstadoSri")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_sri");

                    b.Property<DateTimeOffset?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("FormasPago")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("formas_pago");

                    b.Property<string>("GuiaRemision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("guia_remision");

                    b.Property<string>("IdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion_comprador");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("importe_total");

                    b.Property<string>("InfoAdicional")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("info_adicional");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("numero_autorizacion");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_path");

                    b.Property<decimal>("Propina")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("propina");

                    b.Property<string>("PtoEmi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("pto_emi");

                    b.Property<string>("RazonSocialComprador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social_comprador");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("secuencial");

                    b.Property<string>("SriRespuesta")
                        .HasColumnType("text")
                        .HasColumnName("sri_respuesta");

                    b.Property<string>("TipoIdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_identificacion_comprador");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_descuento");

                    b.Property<decimal>("TotalSinImpuestos")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_sin_impuestos");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorIce")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_ice");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_iva");

                    b.Property<string>("XmlAutorizadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_autorizado_path");

                    b.Property<string>("XmlFirmadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_firmado_path");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAcceso")
                        .IsUnique();

                    b.HasIndex("EmpresaRuc", "EstadoSri", "FechaEmision");

                    b.ToTable("facturas", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.FacturaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cantidad");

                    b.Property<string>("CodigoAuxiliar")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("codigo_auxiliar");

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("codigo_principal");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("descuento");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<decimal?>("IceBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ice_base");

                    b.Property<string>("IceCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ice_codigo");

                    b.Property<decimal?>("IceTarifa")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ice_tarifa");

                    b.Property<decimal?>("IceValor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ice_valor");

                    b.Property<decimal>("IvaBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("iva_base");

                    b.Property<int>("IvaCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("iva_codigo");

                    b.Property<decimal>("IvaTarifa")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("iva_tarifa");

                    b.Property<decimal>("IvaValor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("iva_valor");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioTotalSinImpuesto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_total_sin_impuesto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("facturas_detalle", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "CuentaId")
                        .IsUnique();

                    b.ToTable("idempotency_keys", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.NotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ambiente");

                    b.Property<decimal?>("BaseImponibleIce")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_imponible_ice");

                    b.Property<decimal>("BaseImponibleIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_imponible_iva");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("clave_acceso");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirEstablecimiento")
                        .HasColumnType("text")
                        .HasColumnName("dir_establecimiento");

                    b.Property<string>("DireccionComprador")
                        .HasColumnType("text")
                        .HasColumnName("direccion_comprador");

                    b.Property<string>("DocModificadoClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("doc_modificado_clave_acceso");

                    b.Property<DateOnly>("DocModificadoFecha")
                        .HasColumnType("date")
                        .HasColumnName("doc_modificado_fecha");

                    b.Property<string>("DocModificadoNumero")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("doc_modificado_numero");

                    b.Property<string>("DocModificadoTipo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("doc_modificado_tipo");

                    b.Property<string>("EmpresaRuc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("empresa_ruc");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estab");

                    b.Property<string>("EstadoCorreo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_correo");

                    b.Property<string>("EstadoSri")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_sri");

                    b.Property<DateTimeOffset?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("IdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion_comprador");

                    b.Property<string>("InfoAdicional")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("info_adicional");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("numero_autorizacion");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_path");

                    b.Property<string>("PtoEmi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("pto_emi");

                    b.Property<string>("RazonSocialComprador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social_comprador");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("secuencial");

                    b.Property<string>("SriRespuesta")
                        .HasColumnType("text")
                        .HasColumnName("sri_respuesta");

                    b.Property<string>("TipoIdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_identificacion_comprador");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_descuento");

                    b.Property<decimal>("TotalSinImpuestos")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_sin_impuestos");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorIce")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_ice");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_iva");

                    b.Property<decimal>("ValorModificacion")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_modificacion");

                    b.Property<string>("XmlAutorizadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_autorizado_path");

                    b.Property<string>("XmlFirmadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_firmado_path");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAcceso")
                        .IsUnique();

                    b.HasIndex("EmpresaRuc", "EstadoSri", "FechaEmision");

                    b.ToTable("notas_credito", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.NotaCreditoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cantidad");

                    b.Property<string>("CodigoAuxiliar")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("codigo_auxiliar");

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("codigo_principal");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("descuento");

                    b.Property<decimal?>("IceBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ice_base");

                    b.Property<string>("IceCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ice_codigo");

                    b.Property<decimal?>("IceTarifa")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ice_tarifa");

                    b.Property<decimal?>("IceValor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ice_valor");

                    b.Property<decimal>("IvaBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("iva_base");

                    b.Property<int>("IvaCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("iva_codigo");

                    b.Property<decimal>("IvaTarifa")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("iva_tarifa");

                    b.Property<decimal>("IvaValor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("iva_valor");

                    b.Property<Guid>("NotaCreditoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_credito_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioTotalSinImpuesto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_total_sin_impuesto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id");

                    b.HasIndex("NotaCreditoId");

                    b.ToTable("notas_credito_detalle", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.ParametrosFacturacion", b =>
                {
                    b.Property<string>("EmpresaRuc")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("empresa_ruc");

                    b.Property<bool>("AgenteRetencion")
                        .HasColumnType("boolean")
                        .HasColumnName("agente_retencion");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ambiente");

                    b.Property<string>("CodigoImpuesto")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("codigo_impuesto");

                    b.Property<int>("CodigoPorcentaje")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_porcentaje");

                    b.Property<string>("ContribuyenteEspecial")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("contribuyente_especial");

                    b.Property<string>("ContribuyenteRimpe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contribuyente_rimpe");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estab");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("boolean")
                        .HasColumnName("obligado_contabilidad");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("punto_emision");

                    b.Property<string>("TipoEmision")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo_emision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EmpresaRuc");

                    b.ToTable("parametros_facturacion", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Retencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ambiente");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("clave_acceso");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DireccionSujeto")
                        .HasColumnType("text")
                        .HasColumnName("direccion_sujeto");

                    b.Property<string>("EmpresaRuc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("empresa_ruc");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estab");

                    b.Property<string>("EstadoCorreo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_correo");

                    b.Property<string>("EstadoSri")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_sri");

                    b.Property<DateTimeOffset?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("IdentificacionSujeto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion_sujeto");

                    b.Property<string>("InfoAdicional")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("info_adicional");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("numero_autorizacion");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_path");

                    b.Property<string>("PeriodoFiscal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo_fiscal");

                    b.Property<string>("PtoEmi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("pto_emi");

                    b.Property<string>("RazonSocialSujeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social_sujeto");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("secuencial");

                    b.Property<string>("SriRespuesta")
                        .HasColumnType("text")
                        .HasColumnName("sri_respuesta");

                    b.Property<string>("TipoIdentificacionSujeto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_identificacion_sujeto");

                    b.Property<decimal>("TotalBaseImponible")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_base_imponible");

                    b.Property<decimal>("TotalRetencionIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_retencion_iva");

                    b.Property<decimal>("TotalRetencionRenta")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_retencion_renta");

                    b.Property<decimal>("TotalRetenido")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_retenido");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XmlAutorizadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_autorizado_path");

                    b.Property<string>("XmlFirmadoPath")
                        .HasColumnType("text")
                        .HasColumnName("xml_firmado_path");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAcceso")
                        .IsUnique();

                    b.HasIndex("EmpresaRuc", "EstadoSri", "FechaEmision");

                    b.ToTable("retenciones", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.RetencionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("CodDocSustento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cod_doc_sustento");

                    b.Property<string>("CodigoImpuesto")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("codigo_impuesto");

                    b.Property<string>("CodigoRetencion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("codigo_retencion");

                    b.Property<DateOnly>("FechaEmisionDocSustento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision_doc_sustento");

                    b.Property<string>("NumDocSustento")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("num_doc_sustento");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PorcentajeRetener")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_retener");

                    b.Property<Guid>("RetencionId")
                        .HasColumnType("uuid")
                        .HasColumnName("retencion_id");

                    b.Property<decimal>("ValorRetenido")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_retenido");

                    b.HasKey("Id");

                    b.HasIndex("RetencionId");

                    b.ToTable("retenciones_detalle", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.SecuencialSri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoNumerico")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("codigo_numerico");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmpresaRuc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("empresa_ruc");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("Secuencial")
                        .HasColumnType("bigint")
                        .HasColumnName("secuencial");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_comprobante");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaRuc", "TipoComprobante")
                        .IsUnique();

                    b.ToTable("secuenciales_sri", "facturacion");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Empresa", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.FacturaDetalle", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.Factura", null)
                        .WithMany("Detalle")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.NotaCreditoDetalle", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.NotaCredito", null)
                        .WithMany("Detalle")
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.ParametrosFacturacion", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.Empresa", null)
                        .WithOne()
                        .HasForeignKey("Facturacion.Core.Entidades.ParametrosFacturacion", "EmpresaRuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.RetencionDetalle", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.Retencion", null)
                        .WithMany("Detalle")
                        .HasForeignKey("RetencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.SecuencialSri", b =>
                {
                    b.HasOne("Facturacion.Core.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaRuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Factura", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.NotaCredito", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("Facturacion.Core.Entidades.Retencion", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
